# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: fix-byte-order-marker
-   repo: https://github.com/omnilib/ufmt
    rev: v2.0.1
    hooks:
    -   id: ufmt
        additional_dependencies:
        - black == 22.6.0
        - usort == 1.0.4
